defaults:
  - _self_
  - benchmark:
    - split_mnist
  - strategy:
    - generative
  - model:
    - mlp
  - generative_model:
    - mlp_vae

training:
  train_epochs: 10
  train_mb_size: 128
  eval_mb_size: 128
  optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
    l2: 0.0

seed: 0
device: cuda
device_id: 0
wandb_entity: cl-probing
wandb_project: feature-replay
