defaults:
  - _self_
  - benchmark:
    - split_mnist
  - strategy:
    - naive
  - model:
    - mlp

training:
  train_epochs: 5
  train_mb_size: 128
  eval_mb_size: 128
  optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
    l2: 0.0

seed: 0
device: cuda
device_id: 0
wandb_entity: cl-probing
wandb_project: feature-replay
output_model_path: null