defaults:
  - _self_
  - benchmark:
    - 3s_split_mnist

strategy:
  base: Naive
  plugins: []
  memory_size: 1000
  constant_memory: true
  ewc_lambda: 1.0
  lwf_alpha: 1.0
  lwf_temperature: 1.0

wandb:
  enable: True
  entity: cl-probing
  project: feature-replay

output_dir: null
save_model: false
seed: 0
device: cuda
device_id: 0
