defaults:
  - _self_
  - benchmark:
      - split_fmnist
  - strategy:
      - basic_buffer
  - model:
      - mlp

training:
  train_epochs: 5
  train_mb_size: 128
  eval_mb_size: 128
  optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
    l2: 0.0

wandb:
  enable: True
  entity: cl-probing
  project: feature-replay

seed: 0
device: cuda
device_id: 0
replay: true
ewc_lambda: 0.0
lwf_alpha: 0.0
lwf_temperature: 1.0
stop_replay_after: null

output_dir: null
