name: CI

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Restore virtual environment
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: |
            requirements.txt

      - name: Download pip cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install or update requirements if requirements have changed
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Check code formatting
        run: |
          black --check src tests
          isort --check src tests

      - name: Check linting
        run: |
          flake8 src tests
          mypy src tests

      - name: Run pytest
        run: pytest tests
